const MINIMUM_ALIAS_LENGTH = 2;
const MAX_ALIAS_LENGTH = 17;
const ALIAS_REGEX_PATTERN = `^[a-zA-Z0-9_]{${MINIMUM_ALIAS_LENGTH},${MAX_ALIAS_LENGTH}}$`;

export { MINIMUM_ALIAS_LENGTH as MIN_ALIAS_LENGTH, MAX_ALIAS_LENGTH, ALIAS_REGEX_PATTERN };
